import Link from "next/link";
import { Shell } from "@/components/Shell";
import { db } from "@/lib/db";
import { currentUser } from "@/lib/session";
import { PostActions } from "@/components/PostActions";
import { MediaPreview } from "@/components/MediaPreview";
import { StoryComposer } from "@/components/StoryComposer";
import { StoryRail } from "@/components/StoryRail";
import { PublicLanding } from "@/components/PublicLanding";
export const dynamic="force-dynamic";
export default async function Home(){const me=await currentUser();if(!me)return <PublicLanding/>;let excluded:string[]=[];if(me){const [blocks,mutes]=await Promise.all([db.block.findMany({where:{OR:[{blockerId:me.id},{blockedId:me.id}]},select:{blockerId:true,blockedId:true}}),db.mute.findMany({where:{muterId:me.id},select:{mutedId:true}})]);excluded=[...new Set([...blocks.flatMap((x:{blockerId:string;blockedId:string})=>[x.blockerId,x.blockedId]),...mutes.map((x:{mutedId:string})=>x.mutedId)])].filter(id=>id!==me.id)}const authorFilter:any={status:"ACTIVE"};if(excluded.length)authorFilter.id={notIn:excluded};const stories=await db.story.findMany({where:{expiresAt:{gt:new Date()},author:authorFilter},orderBy:{createdAt:"desc"},take:30,include:{author:{select:{username:true,displayName:true,avatarUrl:true}}}});const posts=await db.post.findMany({where:{visibility:"PUBLIC",author:authorFilter},orderBy:{createdAt:"desc"},take:25,include:{author:{select:{username:true,displayName:true}},media:{orderBy:{position:"asc"}},reactions:{where:{userId:me.id},select:{id:true}},saves:{where:{userId:me.id},select:{id:true}},_count:{select:{reactions:true,comments:true,saves:true}}}});return <Shell><section className="feed"><div className="feedTabs"><b>For You</b><span>Following</span><span>Circles</span><span>Local</span></div><StoryComposer/><StoryRail stories={stories}/>{posts.length===0?<article className="videoCard"><div className="videoStage"><div className="wordmark">OUTS<span>ii</span>DE</div><h1>Come OUTSiiDE.</h1><p>The feed is ready for its first real posts.</p><Link className="create" href="/create">Create your first post</Link></div></article>:posts.map((post:any)=><article className="feedPost" key={post.id}><div className="postAuthor"><Link href={"/u/"+post.author.username}><b>{post.author.displayName}</b><span>@{post.author.username}</span></Link></div><p>{post.caption}</p><MediaPreview media={post.media}/><PostActions id={post.id} likes={post._count.reactions} saves={post._count.saves} initialLiked={post.reactions.length>0} initialSaved={post.saves.length>0}/></article>)}<div className="control"><b>You're in control.</b><span>Why am I seeing this? · Not interested · Show me more like this</span></div></section></Shell>}
