import { notFound } from "next/navigation";
import { Shell } from "@/components/Shell";
import { PorchModeratorPanel } from "@/components/PorchModeratorPanel";
import { PorchRoomModeration } from "@/components/PorchRoomModeration";
import { GiftTray } from "@/components/GiftTray";
import { LiveRoomControls } from "@/components/LiveRoomControls";
import { PorchStageManager } from "@/components/PorchStageManager";
import { LiveRoomLifecycle } from "@/components/LiveRoomLifecycle";
import { LiveRoomMedia } from "@/components/LiveRoomMedia";
import { VerifiedViewingTracker } from "@/components/VerifiedViewingTracker";
import { LiveStats } from "@/components/LiveStats";
import { LiveChat } from "@/components/LiveChat";
import { LiveAnalytics } from "@/components/LiveAnalytics";
import { LivePresence } from "@/components/LivePresence";
import { ReplayManager } from "@/components/ReplayManager";
import { db } from "@/lib/db";
import { currentUser } from "@/lib/session";
import { FavoriteButton } from "@/components/FavoriteButton";
import { ViewerLiveScreen } from "@/components/ViewerLiveScreen";
export const dynamic="force-dynamic";
export default async function PorchRoom({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const me=await currentUser();const room=await db.porchRoom.findUnique({where:{slug},include:{members:{include:{user:{select:{username:true,displayName:true}}}},_count:{select:{members:true}}}});if(!room)notFound();const myMember=me?room.members.find(m=>m.userId===me.id):undefined;const host=myMember?.role==="HOST";return <Shell><section className="page"><span className="eyebrow">The Porch · {room.status}</span><h1>{room.title}</h1><p className="lede">{room.description}</p>{room.scheduledFor&&<p>Scheduled: {room.scheduledFor.toLocaleString()}</p>}<p>{room._count.members} people in the room</p>{me&&!host&&<FavoriteButton type="porch" id={room.id}/>}<div className="porchPeople">{room.members.map(m=><div key={m.userId}><b>{m.user.displayName}</b><span>@{m.user.username} · {m.role.toLowerCase()}</span></div>)}</div>{host&&<LiveRoomLifecycle slug={room.slug} status={room.status}/>} {host&&<LiveRoomControls slug={room.slug} screenSharing={room.screenSharing} initialSettings={{chatEnabled:room.chatEnabled,followersOnlyChat:room.followersOnlyChat,slowModeSeconds:room.slowModeSeconds,giftsEnabled:room.giftsEnabled,musicEnabled:room.musicEnabled}}/>}<ReplayManager slug={room.slug} host={host} status={room.status}/><LivePresence slug={room.slug} status={room.status}/><LiveAnalytics slug={room.slug} status={room.status} host={host}/><LiveStats slug={room.slug} status={room.status} startedAt={room.startedAt?.toISOString()??null}/>{host?<><VerifiedViewingTracker slug={room.slug} status={room.status} host={true}/><LiveRoomMedia slug={room.slug} roomType={room.roomType} status={room.status} meId={me?.id??""} initialMembers={room.members} myRole={myMember?.role??null}/><PorchStageManager slug={room.slug} members={room.members} role={myMember?.role??null} stageSize={room.stageSize}/>{room.status==="LIVE"&&myMember&&<LiveChat slug={room.slug} role={myMember.role}/>}</>:me&&myMember?<ViewerLiveScreen room={room} meId={me.id} myRole={myMember.role} hostId={room.members.find(m=>m.role==="HOST")?.userId??""}/>:null}<PorchModeratorPanel slug={room.slug} members={room.members} host={host}/><PorchRoomModeration slug={room.slug} members={room.members} role={myMember?.role??null}/></section></Shell>}