"use client";
import { FormEvent,useEffect,useState } from "react";
import { useRouter } from "next/navigation";
export default function EditProfile(){
 const router=useRouter();const [user,setUser]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/auth/me").then(r=>r.json()).then(d=>{if(!d.user)router.replace("/login");else setUser(d.user)})},[router]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch("/api/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:f.get("displayName"),bio:f.get("bio"),profileVideoUrl:f.get("profileVideoUrl"),privacy:f.get("privacy"),messagePrivacy:f.get("messagePrivacy"),commentPrivacy:f.get("commentPrivacy"),mentionPrivacy:f.get("mentionPrivacy"),liveInvitePrivacy:f.get("liveInvitePrivacy"),hideActivity:f.get("hideActivity")==="on",hideConnections:f.get("hideConnections")==="on"})});const d=await r.json();if(!r.ok)return setError(d.error);router.push("/u/"+d.user.username);}
 if(!user)return <main className="auth"><div className="authCard">Loading…</div></main>;
 return <main className="auth"><div className="authCard"><h1>Edit profile</h1><form onSubmit={save}><label>Display name<input name="displayName" defaultValue={user.displayName} required maxLength={60}/></label><label>Bio<input name="bio" defaultValue={user.bio??""} maxLength={160}/></label><label>Profile video URL<input name="profileVideoUrl" defaultValue={user.profileVideoUrl??""} type="url"/></label><label>Account<select name="privacy" defaultValue={user.privacy??"PUBLIC"}><option value="PUBLIC">Public</option><option value="PRIVATE">Private</option></select></label>{[["messagePrivacy","Who can message me"],["commentPrivacy","Who can comment"],["mentionPrivacy","Who can mention me"],["liveInvitePrivacy","Who can invite me to lives"]].map(([name,label])=><label key={name}>{label}<select name={name} defaultValue={user[name]??"EVERYONE"}><option value="EVERYONE">Everyone</option><option value="FOLLOWERS">Followers</option><option value="FRIENDS">Friends</option><option value="NOBODY">Nobody</option></select></label>)}<label><input type="checkbox" name="hideActivity" defaultChecked={user.hideActivity}/> Hide my activity</label><label><input type="checkbox" name="hideConnections" defaultChecked={user.hideConnections}/> Hide follower/following lists</label>{error&&<div className="formError">{error}</div>}<button>Save profile</button></form></div></main>;
}
